config/routes.rb
Rails.application.routes.draw do
  resources :venues, only: [:new, :create, :show, :edit, :index]
  resources :users
  root 'events#index'

  get "upcoming" => "events#index"
  get "myevent" => "events#mine"

  resources :events do
    resources :tickets
    get 'purchase_ticket' => 'tickets#purchase'
    put 'buy_ticket' => 'tickets#buy'

    collection do
      get 'search/:q', :action => 'search', :as => 'search'
    end

    get 'modify' => 'events#modify'
    put 'publish' => 'events#publish'
  end

  resources :sessions, only: [:new, :create]
  delete  'log_out' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_inclusion_of :name, in: ['Entertainment', 'Learning', 'Everything Else']
  validates_uniqueness_of :name
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :venue
  belongs_to :category
  has_many :ticket_types

  validates_presence_of :extended_html_description, :venue, :category, :starts_at
  validates_uniqueness_of :name, uniqueness: {scope: [:venue, :starts_at]}

  def self.upcoming
    where("ends_at >= ? and publish_status = true", Time.zone.now).order(:starts_at)
  end

  def self.search(term)
    where('name LIKE ?', "%#{term}%")
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
    validates_inclusion_of :name, in: ['Saigon', 'Ha Noi', 'Binh Thuan', 'Da Nang', 'Lam Dong']
    validates_uniqueness_of :name
end

app/models/ticket_type.rb
class TicketType < ActiveRecord::Base
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true

  def to_s
    name
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :region
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    return @current_user if @current_user

    if session[:user_id]
      @current_user = User.find_by_id(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.upcoming
	end

	def show
		@event = Event.find(params[:id])
	end

	def search
		@events_matches = Event.all
		if params[:term]
			@events_matches = Event.search(params[:term])
		end
	end

	def new
		@event = Event.new
	end

	def edit 
		@event = Event.find_by_id(params[:id])
    @ticket_types = TicketType.where('event_id = ?', @event.id)
	end

	def publish
		event = Event.find_by_id(params[:event_id])
    ticket_types = TicketType.where('event_id = ?', event.id)
    if ticket_types.empty? == false 
		  event.publish_status = true
		  event.save!
    end
		redirect_to root_path
	end

	def create
		@event = Event.new(event_params)
		@event.user_id = current_user.id
		respond_to do |format|
			if @event.save
        @ticket_types = TicketType.where('event_id = ?', @event.id)
				format.html { render :edit, :id => @event.id, notice: 'Event created success' }
				format.json { render :edit, status: :created, location: @event }
			else
				format.html { render :new }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	def modify
    if current_user == nil
      flash[:error] = 'Permission denined'
      redirect_to root_path
    else
		  @event = Event.find_by_id(params[:event_id])
    end
	end

	def update
		@event = Event.find_by_id(params[:id])
		respond_to do |format|
			if @event.update(event_params)
				format.html { render :edit, :id => @event.id, notice: 'Event updated success' }
				format.json { render :show, status: :ok, location: @food_item }
			else
				format.html { render :new }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	def mine
		@events = Event.where("user_id = ?", current_user.id)
	end

	private
	def event_params
		params.require(:event).permit(:name, :extended_html_description, :venue_id, :category_id, :starts_at, :ends_at) 
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user
      if @user.authenticate(params[:password])
        flash[:success] = "You signed in as " + @user.name
        session[:user_id] = @user.id
        redirect_to root_path
      else
        flash.now[:error] = "Incorrect password"
        render 'new'
      end
    else
      flash.now[:error] = "Email not found " + params[:email]
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: {error: "Logged out"}
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def purchase 
    @event_item = Event.find(params[:event_id])
  end

  def new
    @event = Event.find(params[:event_id])
    @ticket_type = TicketType.new 
    @ticket_type.event_id = params[:event_id]
  end

  def buy
    # Decrease available ticket
    ticket = TicketType.find_by_id(params[:ticket_id])
    if ticket != nil
      if ticket.max_quantity < params[:quantity].to_i
        flash[:error] = 'Not enough ticket for buying'
      else
        ticket.max_quantity = ticket.max_quantity - params[:quantity].to_i
        ticket.save!
        if params[:quantity].to_i != 0
          flash[:success] = 'Purchased ticket ' + ticket.name
        end
      end
    end

    redirect_to event_purchase_ticket_path(params[:event_id]) 
  end

  def create

    ticket_from_db = TicketType.find_by(name: tickets_params[:name], event_id: params[:event_id])

    if ticket_from_db != nil
      flash[:error] = 'This ticket is already created for current event'
      redirect_to new_event_ticket_path(params[:event_id])
    else
      @ticket_type = TicketType.new(tickets_params)
      @ticket_type.event_id = params[:event_id]
      @event = Event.find(params[:event_id])
      respond_to do |format|
        if @ticket_type.save
          format.html { redirect_to edit_event_path([@event.id]), notice: 'Tickets is added' }
          format.json { render :edit, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @ticket_type.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
  def tickets_params
    params.require(:ticket).permit(:name, :max_quantity, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new(email: params[:email])
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Welcome to qTick, " + @user.name
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def new
    @venue = Venue.new
  end

  def show
    @venue = Venue.find(params[:id])
  end

  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was created successfully' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  def venue_params
    params.require(:venue).permit(:name, :full_address, :region_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
		{ success: 'alert-success alert-top', error: 'alert-danger alert-top', notice: 'alert-warning alert-top'}[flash_type.to_sym]
	end

	def flash_messages(opts = {})
		flash.map do |msg_type, message|
			content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}") do
				content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
			end
		end.join.html_safe
	end
end

app/helpers/events_helper.rb
module EventsHelper
  def header_background_image_url
    image_path('color-me-run.jpg')
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/events/_card.html.erb
<div class="col-md-6">
  <%= link_to event_path(event) do %>
    <div class="card">
      <img class="card-img-top" src="<%= event.hero_image_url %>">
      <div class="card-block">
        <h4 class="card-title"><%= event.name %></h4>
        <p class="card-text">
          <%= event.extended_html_description %>
        </p>
      </div>
    </div>
  <% end %>
</div>  

app/views/events/_change.html.erb
<div class="col-md-6">
  <%= link_to edit_event_path(event) do %>
    <div class="card">
      <img class="card-img-top" src="<%= event.hero_image_url %>">
      <div class="card-block">
        <h4 class="card-title"><%= event.name %></h4>
        <p class="card-text">
          <%= event.extended_html_description %>
        </p>
      </div>
    </div>
  <% end %>
</div>  

app/views/events/_form.html.erb
<div class="container">
  <%= form_for event do |f| %>
    <% if @event.errors.size > 0 %>
      <div class="alert alert-danger">
        <%= @event.errors.full_messages.to_sentence %>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label 'Event name' %>
      <%= f.text_field :name, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label 'Description' %>
      <%= f.text_area :extended_html_description, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label :venue_id %>
      <%= f.select :venue_id, Venue.all.map{|ele| [ele.name, ele.id]}, {}, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.select :category_id, Category.all.map{|ele| [ele.name, ele.id]}, {}, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label 'Begin (mm/dd/yyyy, HH:MM)' %>
      <%= f.datetime_field :starts_at, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label 'End (mm/dd/yyyy, HH:MM)' %>
      <%= f.datetime_field :ends_at, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="container">
	<br>
	<br>
	<br>
	<h1>Publish Events</h1>
	<hr>

	<div class="card">
		<div class="card-header">	
			<%= @event.name %>
		</div>

		<div class="card-block">
			<p class="card-text">
				<%= @event.extended_html_description %>
			</p>

			<ul class="list-group list-group-flush">
				<li class="list-group-item"><strong>Type: </strong><%= @event.category.name %> </li>
				<li class="list-group-item"><strong>At: </strong><%= @event.venue.name %> </li>
				<li class="list-group-item"><strong>From: </strong><%= @event.starts_at.strftime(" %A, %d %b %Y %l:%M %p")%></li>
				<li class="list-group-item"><strong>To: </strong><%= @event.ends_at.strftime("%A, %d %b %Y %l:%M %p")%></li>

				<% if @ticket_types %>
					<% @ticket_types.each do |tick| %>
          <li class="list-group-item">Ticket: <%= tick.name %> | Price <%= tick.price %> | Quantity <%= tick.max_quantity %></li>
					<% end %>
				<% end %>

			</ul>
			<br>

      <ul class="nav nav-pills card-footer-pills">
        <% if @ticket_types.empty? == false %>
        <li class="nav-item">
          <%= form_tag event_publish_path(@event.id), method: :put, remote: true do %>
            <%= submit_tag("Publish", class: "btn btn-success") %>
          <% end %>
        </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Modify", event_modify_path(event_id: @event.id), class: "btn btn-success" %>
        </li>

        <li class="nav-item">
          <%= link_to "Tickets", new_event_ticket_path(event_id: @event.id), class: "btn btn-success" %>
        </li>
      </ul>
		</div>
	</div>
</div>

app/views/events/mine.html.erb
<div class='events-header' style='background-image: url(<%= header_background_image_url %>)'>
  <div class="container">
    <h2> Your own events </h2>
  </div>
</div>
<div class="container-fluid events-list">
  <% if @events %>
    <% @events.each do |e| %>
      <%= render partial: 'change', locals: {event: e} %>
    <% end %>
  <% end %>
</div>

app/views/events/modify.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <h1>Modification Events</h1>
  <%= render 'form', event: @event %>
</div>

app/views/events/new.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <h1>New Events</h1>
  <%= render 'form', event: @event %>
</div>

app/views/events/search.html.erb
<div class='events-header' style='background-image: url(<%= header_background_image_url %>)'>
  <div class="container">
    <h2> Search </h2>
  </div>
</div>
<div class="container-fluid events-list">
  <% if @events_matches %>
    <% @events_matches.each do |e| %>
      <%= render partial: 'card', locals: {event: e} %>
    <% end %>
  <% else %>
  <h2>Event not found</h2>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container-fluid no-pad events-detail">
  <div class="row no-pad">
    <div class="col-md-3 sidebar">
      <p>
        <%= fa_icon 'ticket' %>
        Price
      </p>
      <h1> Hot Events </h1>
      <div class="ticket-list">
        <% @event.ticket_types.each do |ticket_type| %>
          <div class="row">
            <div class="col-md-6">
              <%= ticket_type.name %>
            </div>

            <div class="col-md-6 price text-right">
              <%= number_to_currency(ticket_type.price, unit: 'VND', precision: 0) %>
            </div>
          </div>
          <div class="clearfix"></div>
        <% end %>
        <br>
        <%= link_to 'BOOK NOW', event_purchase_ticket_path(event_id: @event.id), class: 'btn btn-lg btn-block btn-danger' %>
      </div>
    </div>
    <div class="col-md-9 event-content">
      <div class="hero-img hidden-sm-down" style="background-image: url(<%= @event.hero_image_url %>); background-size: cover;"> </div>
      <div class="container">
        <h3> <%= @event.name %> </h3>
        <div class="pull-left">
          <%= fa_icon 'clock-o' %>
        </div>
        <div class="time-details"> 
          <%= @event.starts_at.strftime('%A, %d %b %Y %l:%M %p') %> 
        </div>

        <div class="pull-left">
          <%= fa_icon 'map-marker' %>
        </div>
        <div class="venue-details">
         <%= @event.venue.name %>
         <br/>
         <%= @event.venue.full_address %>
        </div>

        <div class="img-spacer">
          <%= image_tag 'shadow-top.png' %>
        </div>
        <div class="extended-description">
          <%= @event.extended_html_description.html_safe %>
        </div>

      </div>  
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>qTick</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
			<a class="navbar-brand" href="<%= root_path %>">qTick</a>
			<ul class="nav navbar-nav">
				<% if current_user %>

				<li class="nav-item">
					<%= link_to "Logout", log_out_path, method: "delete" , class: "nav-link" %>
				</li>

				<li class="nav-item">
					<%= link_to "Profile", user_path(id: current_user.id), class: "nav-link" %>
				</li>

				<li class="nav-item">
					<%= link_to "Event", new_event_path, class: "nav-link" %>
				</li>

				<li class="nav-item">
					<%= link_to "Mine", myevent_path, class: "nav-link" %>
				</li>

				<li class="nav-item">
					<%= link_to "Venue", new_venue_path, class: "nav-link" %>
				</li>

				<% else %>
				<li class="nav-item">
					<%= link_to "Sign Up", new_user_path, class: "nav-link" %>
				</li>

				<li class="nav-item">
					<%= link_to "Login", new_session_path, class: "nav-link" %>
				</li>
				<% end %> 
			</ul>
		</nav>  
		<%= yield %>
	</body>
	<footer>
		<%= flash_messages %>
	</footer>
</html>

app/views/tickets/_form.html.erb
<div class="container">
  <%= form_for :ticket, :url => {:action => "create", :id => @ticket} do |f| %>
    <% if @ticket_type.errors.size > 0 %>
      <div class="alert alert-danger">
        <%= @ticket_type.errors.full_messages.to_sentence %>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label :max_quantity %>
      <%= f.number_field :max_quantity, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.submit "Add", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/tickets/new.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <h1>Tickets for: <%= @event.name %></h1>
  <%= render 'form', ticket: @ticket_type %>
</div>

app/views/tickets/purchase.html.erb
<div class="container-fluid tickets-buy">
  <div class="row tickets-header">
    <div class="col-xs-12 col-md-11 col-md-offset-1">
      <h3> <%= @event_item.name %> </h3>
      <div class="pull-left">
        <%= fa_icon 'map-marker' %>
      </div>
      <div class="venue-details">
       <%= @event_item.venue.name %>
       <br/>
       <%= @event_item.venue.full_address %>
      </div>

      <div class="pull-left">
        <%= fa_icon 'clock-o' %>
      </div>
      <div class="time-details"> 
        <%= @event_item.starts_at.strftime('%A, %d %b %Y %l:%M %p') %> 
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-11 col-md-offset-1">  
      <table class="table">
        <th> Ticket Type </th>
        <th> Unit Price </th>
        <th> Quantity </th>
        <th> Available Tickets </th>
        <th> </th>

      
        <% @event_item.ticket_types.each do |type| %>
        <tr>
          <%= form_tag event_buy_ticket_path, {method: :put} do %>
            <div class='form-inline'>
              <td> <%= type.name %> </td>
              <td> <%= number_to_currency(type.price, unit: 'VND ', precision: 0) %> </td>
              <td> <%= select_tag :quantity, options_for_select(0..10) %></td> 
              <td> <%= type.max_quantity %></td> 
              <%= hidden_field_tag :ticket_id , type.id %>
              <td>
                <%= submit_tag 'Buy', class: 'btn btn-success' %>
              </td> 
            </div>
          <% end %> 
        </tr>
        <% end %> 
      </table>
    </div>
  </div>
</div>  

app/views/users/new.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <h1>Sign Up</h1>
  <hr>
  <%= form_for @user do |f| %>
    <% if @user.errors.size > 0 %>
      <div class="alert alert-danger">
        <%= @user.errors.full_messages.to_sentence %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control'%>
    </div>
    <%= f.submit "Sign Up", class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <br>
  <% if current_user %>
  <h1>Profile</h1>
  <hr>
  <h3><%= current_user.name %></h3>
  <p><%= current_user.email %></p>
  <% end %>
</div>

app/views/venues/index.html.erb
<div class='events-header' style='background-image: url(<%= header_background_image_url %>)'>
  <div class="container">
    <h2> Discover upcoming events </h2>
    <%= form_tag(search_events_path(:term), :method => "get", id: "search-form", html: {class: 'form-group'}) do %>
    <%= text_field_tag :term, params[:term], class: 'form-control mr-sm-2', placeholder: "Search for events, shows, courses..." %>
    <% end %>
  </div>
</div>
<div class="container-fluid events-list">
  <% @events.in_groups_of(3) do |g| %>
  <div class="row">
    <% g.compact.each do |e| %>
    <%= render partial: 'card', locals: {event: e} %>
    <% end %>
  </div>  
  <% end %>
</div>

app/views/venues/new.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <h1>New Venues</h1>
  <hr>
  <%= form_for @venue do |f| %>
    <% if @venue.errors.size > 0 %>
      <div class="alert alert-danger">
        <%= @venue.errors.full_messages.to_sentence %>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label :full_address %>
      <%= f.text_area :full_address, class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label :region_id %>
      <%= f.select :region_id, Region.all.map{|ele| [ele.name, ele.id]}, {}, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Create", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/venues/show.html.erb
<div class="container">
	<br>
	<br>
	<br>
	<h1>Venues</h1>
	<hr>

	<div class="card">
		<div class="card-header">	
			<%= @venue.name %>
		</div>

		<div class="card-block">
			<p class="card-text">
				<%= @venue.full_address %>
			</p>

			<ul class="list-group list-group-flush">
        <li class="list-group-item"><strong><%= @venue.region.name %></strong></li>
			</ul>
		</div>
	</div>
</div>